### ISSUE TITLE
I broke /searchpost somehow

### ISSUE THREAD

**Issue by SarynSummer** [SarynSummer/Transfer-App#11]
I'm 99% sure it's because the drop-down lists are being mapped is not correctly passing the selected values to the server API as it appears to work but is sending blank data. If you can start with that it would be excellent. You'll see what I mean when you see the form on /searchpost inside /pages

(not /searchresults which is in components and renders the lower part this is all in the top bit)

**Comment by Pavani-Vithala** [comment]
Searchpost functionality is working fine.This issue can be closed
